[project]
authors = ["Jared Bard <jabard89@gmail.com>"]
channels = ["conda-forge","bioconda"]
description = "scripts for R and to tidy data"
name = "bardlab_rcode"
platforms = ["osx-64","osx-arm64","win-64","linux-64"]
version = "0.1.0"
license = "MIT"

[tasks]

[dependencies]
python = ">=3.10, <3.12"
numpy = "*"
pandas = "*"
